### ISSUE TITLE
[Bug] Zooming into nested editors should not zoom the parent editors

### ISSUE THREAD

**Issue by miroiu** [BAndysc/nodify-avalonia#1]
**To Reproduce**
1. create an Operation Graph in the Calculator example
2. zoom in on the created editor

**Screenshots**
![zoom](https://github.com/BAndysc/nodify-avalonia/assets/12727904/10bffc4d-3f00-41b7-bdad-9403ea4b3725)

**Does it happen in WPF version?**
No.

**Comment by BAndysc** [comment]
Fixed: https://github.com/BAndysc/nodify-avalonia/commit/53c9adf51d520775ae266678e1d3bb6185ee577e
