### ISSUE TITLE
[Bug] Can't resize grouping nodes

### ISSUE THREAD

**Issue by miroiu** [BAndysc/nodify-avalonia#11]
**Describe the bug**
The grouping node can't be resized properly.

**Screenshots**

![resize-grouping-node](https://github.com/BAndysc/nodify-avalonia/assets/12727904/dca04aa3-7b38-4865-b0fa-e9c4570948cc)

**Does it happen in WPF version?**
No.

**Comment by BAndysc** [comment]
Thanks, fixed in https://github.com/BAndysc/nodify-avalonia/commit/51ab82cbd1090d7ee026727787a32bf54bdaa0a6
