### ISSUE TITLE
[Bug] Releasing mouse right button when panning is not handled properly

### ISSUE THREAD

**Issue by miroiu** [BAndysc/nodify-avalonia#12]
**Describe the bug**
In the state machine example if you right-click to pan and release the mouse you will always see the context menu.

**Expected behavior**
The context menu should be visible only if the mouse moves within the `NodifyEditor.HandleRightClickAfterPanningThreshold` pixels threshold.

**Screenshots**

![right-click](https://github.com/BAndysc/nodify-avalonia/assets/12727904/edf554c1-9f9f-4850-a0f3-6de9feb87595)

**Does it happen in WPF version?**
No.

**Comment by BAndysc** [comment]
Fixed in https://github.com/BAndysc/nodify-avalonia/commit/5c4ad9e34360eb5efdbc834ac468f6ec809dcc7f
