### ISSUE TITLE
[Bug] Right-clicking near the edge of the window will trigger auto panning

### ISSUE THREAD

**Issue by miroiu** [BAndysc/nodify-avalonia#13]
**Describe the bug**
Right clicking near the edge of the window in the state machine example will trigger auto panning.

**Screenshots**

![auto-panning](https://github.com/BAndysc/nodify-avalonia/assets/12727904/6bce5add-e139-483e-8aea-81bedaba1772)

**Does it happen in WPF version?**
No.

**Additional context**
May be related to #12

**Comment by BAndysc** [comment]
Right, it was related to #12. Fixed
