### ISSUE TITLE
[Bug] StateMachine Example Does Not Create Connections

### ISSUE THREAD

**Issue by h43r1c** [BAndysc/nodify-avalonia#14]
**Describe the bug**
When opening the project in VS 17.8.3, the "Nodify.StateMachine" example project does not create connections between StateNodes.

**To Reproduce**
1) Clone project
2) Open Nodify.sln
3) Set "Nodify.StateMachine" to the start up project and Run
4) Create new StateNode "New State"
5) Drag Connection from "Enter" to "New State"

**Expected behavior**
Connections to be created between states when dragging connections.

**Does it happen in WPF version?**
No, upstream the connections are created.

**Comment by h43r1c** [comment]
This behavior was not present in v5.2.0.1 (connections are created) but exists in v6.0.0 and the default branch.

**Comment by BAndysc** [comment]
Fixed sticky connections in https://github.com/BAndysc/nodify-avalonia/commit/5b462392f53636346bdf2b73fa653485574443e6
