### ISSUE TITLE
[Bug]Can not connect node in StateMachine example

### ISSUE THREAD

**Issue by phamviethuy** [BAndysc/nodify-avalonia#16]
**Describe the bug**
Can not connect node in StateMachine example

**To Reproduce**
Press a node then connect to another node

**Expected behavior**
Can connect node

**Screenshots**
![image](https://github.com/BAndysc/nodify-avalonia/assets/42407610/915f3e55-6fb0-4d69-9ee7-9b4adfe2017b)

**Comment by BAndysc** [comment]
Fixed sticky connections in https://github.com/BAndysc/nodify-avalonia/commit/5b462392f53636346bdf2b73fa653485574443e6

**Comment by phamviethuy** [comment]
nice
