### ISSUE TITLE
[Bug] Cannot use marquee selection inside comment nodes

### ISSUE THREAD

**Issue by miroiu** [BAndysc/nodify-avalonia#2]
**To Reproduce**
1. create a few nodes in the Playground app
2. comment the nodes
3. try to select the nodes inside the comment with the selection rectangle

**Expected behavior**
Clicking and dragging should start the selection.

**Does it happen in WPF version?**
No.

**Comment by BAndysc** [comment]
Fixed: https://github.com/BAndysc/nodify-avalonia/commit/e72c773551807b2f596d13447596f18f1259e939
