### ISSUE TITLE
[Bug] Starting a pending connection and pressing the Escape key throws an exception

### ISSUE THREAD

**Issue by miroiu** [BAndysc/nodify-avalonia#3]
**To Reproduce**
1. start a pending connection
2. press Escape

**Expected behavior**
The pending connection should be canceled.

**Does it happen in WPF version?**
No.

**Comment by BAndysc** [comment]
Fixed: https://github.com/BAndysc/nodify-avalonia/commit/1c0620668f7d34a050b064fae38a368a8f02ba98
