### ISSUE TITLE
[Bug] Starting any example app throws an exception

### ISSUE THREAD

**Issue by miroiu** [BAndysc/nodify-avalonia#4]
**To Reproduce**
Start any application from a clean clone of the repo.

**Screenshots**
![image](https://github.com/BAndysc/nodify-avalonia/assets/12727904/b597584e-76b4-4e3b-b7df-c69ccbe85a37)

**Does it happen in WPF version?**
No.

**Comment by BAndysc** [comment]
Fixed https://github.com/BAndysc/nodify-avalonia/commit/2a059a3a6e50b70661863b8eaa2ae792723467a1
