### ISSUE TITLE
[Bug] Cannot use marquee selection and pan at the same time

### ISSUE THREAD

**Issue by miroiu** [BAndysc/nodify-avalonia#5]
**To Reproduce**
1. click and drag to start a marquee selection
2. right-click to pan while still having the marquee selection active

**Expected behavior**
I should be able to pan without losing my selection.

![select-pan](https://github.com/BAndysc/nodify-avalonia/assets/12727904/89c33094-0e9b-4e05-b83d-ce492db47428)

**Does it happen in WPF version?**
No.

**Comment by BAndysc** [comment]
Fixed: https://github.com/BAndysc/nodify-avalonia/commit/72a9a011252982ad119d766fba50b5a2926bcdc4
