### ISSUE TITLE
[Bug] Dragging a node near the edge of the screen does not automatically pan the viewport

### ISSUE THREAD

**Issue by miroiu** [BAndysc/nodify-avalonia#6]
**To Reproduce**
Drag a node to the edge of the screen or outside the screen.

**Expected behavior**
The editor should automatically pan in the direction you are dragging.

**Does it happen in WPF version?**
No.

**Comment by BAndysc** [comment]
Found a way to mimic WPF's behaviour when it comes to pointer capture, so it should work just like in WPF now :)
