### ISSUE TITLE
[Bug] The selection rectangle stops updating when the cursor is outside the window

### ISSUE THREAD

**Issue by miroiu** [BAndysc/nodify-avalonia#7]
**To Reproduce**
Start a marquee selection then move and **stop** the cursor outside the screen.

**Screenshots**
![selection](https://github.com/BAndysc/nodify-avalonia/assets/12727904/2c219bb8-c7fd-4be5-ad92-68974886fc2c)

**Does it happen in WPF version?**
No.

**Comment by BAndysc** [comment]
Fixed in https://github.com/BAndysc/nodify-avalonia/commit/a914ac63eeed92b025343b7b7e00d924f965a942, forgot to close the issue :)
