### ISSUE TITLE
[Question] Is the entire rendering done in cross platform SkiaSharp?

### ISSUE THREAD

**Issue by GeorgeS2019** [BAndysc/nodify-avalonia#8]

**Comment by BAndysc** [comment]
NodifyAvalonia doesn't use Skia directly, tho it is a library for Avalonia, which **does** use Skia underneath for rendering, just like WPF uses DirectX underneath. Avalonia is cross platform and runs on all desktop platforms (Winddows, macOS, Linux), but also web (web assembly), mobile (Android, iOS, iPadOS) and even more (I.e. Tinzen, tvOS...). It is possible to draw directly with Skia when writing Avalonia controls, however then all the input state (mouse, keyboard) needs to be managed manually. This is not feasible for such a big control. I hope it answers the question.
